

ALTER TABLE produtosdistribuidor ADD PRIMARY KEY(id);
ALTER TABLE produto ADD PRIMARY KEY(id);
ALTER TABLE orcamento ADD PRIMARY KEY(id);
ALTER TABLE fisica ADD PRIMARY KEY(id);
ALTER TABLE imagensproduto ADD PRIMARY KEY(id);
ALTER TABLE endereco ADD PRIMARY KEY(id);
ALTER TABLE telefone ADD PRIMARY KEY(id);


ALTER TABLE telefone CHANGE id id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE produtosdistribuidor CHANGE id id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE produto CHANGE id id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE orcamento CHANGE id id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE fisica CHANGE id id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE imagensproduto CHANGE id id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE endereco CHANGE id id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
